---
driver:
  name: vagrant
  network:
    - ['private_network', { type: 'dhcp' }]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[hadouken::default]
    attributes:
